baseURL = 'https://benevolent-bavarois-370a31.netlify.app/'
languageCode = 'es'
title = 'ALBERTORG'
theme = 'bilberry'

[params]
  avatar = "/images/log02.png"  # Ruta relativa desde static/

[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEDRAFTS = "true"
  GIT_SUBMODULES = "true"
